@host = localhost
@port = 3000
@uri = http://{{host}}:{{port}}
@contentType = application/json

### getHello
// @name getHello

GET {{uri}}
Content-Type: application/json

### getHelloEnv
// @name getHelloEnv

GET {{uri}}/env
Content-Type: application/json

